[package]
name = "detat"
version = "0.1.0"
authors = ["taskie <t@skie.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chardet = "0.2.4"
encoding = "0.2.33"
env_logger = "0.7.1"
log = "0.4.8"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
structopt = "0.3.14"
